# 先执行：mvn -pl geo-file-service -am -DskipTests package
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY geo-file-service/target/geo-file-service.jar app.jar
ENV JAVA_OPTS="-Xmx256m"
EXPOSE 8083
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
