# 先执行：mvn -pl geo-analysis-service -am -DskipTests package
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY geo-analysis-service/target/geo-analysis-service.jar app.jar
ENV JAVA_OPTS="-Xmx1024m"
EXPOSE 8082
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
